version: '3'

services:
  php:
    container_name: php
    build: docker/php
    volumes:
      - ./../../server:/var/www/:cached

  node:
    container_name: node
    build: docker/node
    volumes:
      - ./../../server:/project:cached
    tty: true

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./../../server:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    working_dir: /var/www
    depends_on:
      - php
      - node

  mysql:
    image: mariadb:10.4
    container_name: laraveldb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel-vue-docker
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
